### PR TITLE
Changed load from restart file

### PR DESCRIPTION
**Pull request by joakim-hove**
Previously the `init_from_restart_file( )` function loaded a hardcoded list of keywords from the restart file, with this PR the keywords to load is passed to the method as a `std::map`. This way the writing to and reading from restart files is symmetric - and 100% under the control application layer.

I am sorry to say that the git history was beyond salvation, and all the work has been squashed to one single commit (with a long commit message). There will be more janitorial refactoring of this type in the the output layer - also including updates to the reference data, but I took a break now.

opm-simulators: https://github.com/OPM/opm-simulators/pull/999

### CODE REVIEW

**Comment by atgeirr** [comment]
I have not read the code, but from the description it sounds like a very good step forward!

**Comment by joakim-hove** [comment]
> I have not read the code, but from the description it sounds like a very good step forward!

Good - let us hope you are right.

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-simulators=999 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-simulators=999 please

**Comment by joakim-hove** [comment]
OK - this should go through a massive rewrite git-wise, but apart from that it should be ~ready for review.

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-simulators=999 please

**Comment by joakim-hove** [comment]
Lo and behold - this is  [green](https://ci.opm-project.org/job/opm-simulators-PR-builder/226/) at last - and I would like to merge it along with OPM/opm-simulators#999

@jokva / @pgdr : comments?!

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-simulators=999 please

**Pull request merged**
