### PR TITLE
Added ability to save restart fields in double.

### PR DESCRIPTION
**Pull request by joakim-hove**
Observe that just the scaling between SI units and output units is enough to loose bitwise equality.

### CODE REVIEW

**Comment by atgeirr** [comment]
> Observe that just the scaling between SI units and output units is enough to loose bitwise equality.

While not bitwise equal I expect that it will be close enough that the solvers (linear and nonlinear) will never make different choices (in original and restarted run) because of this. Thanks for providing the ability!

**Comment by joakim-hove** [comment]
For people investigating restart I encourage you to look at the `RestartIO::load()` and `RestartIO::save()` functions, using those functions you can completely bypass deck configuration of restart times.

**Comment by atgeirr** [comment]
Just tested this -- works beautifully!

**Comment by joakim-hove** [comment]
> Just tested this -- works beautifully!

Good - I am glad to hear!

**Pull request merged**
