### PR TITLE
EclipseIO::writeTimestep ensure summary data.

### PR DESCRIPTION
**Pull request by joakim-hove**
There was an incorrect early return in the writeTimestep( ) routine. The consequence of that was that summary data was not written for sub-report time resolution. This will require reference data updates:

1. The evaluation of total variables `WOPT = \int_{t_1}^{t_2} dt WOPR` which will be integrated over a complete report step, instead of subdividing the integeral over the timesteps of the simulator.
2. There will be too few time steps in the summary data file.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this with downstreams update_data please

**Comment by joakim-hove** [comment]
jenkins run norne spe polymer please update_data please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams update_data please

**Comment by joakim-hove** [comment]
@akva2: The PR: https://github.com/OPM/opm-data/issues/178 looks fine, but the changes in *this* PR will mandate updates also to to the norne++ reference data - is that within scope of the `update_data` attribute?

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-data=178 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-data=178 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-data=177 please

**Comment by akva2** [comment]
currently not supported, not necessarily out of scope but i have only considered regression tests for now.

**Comment by joakim-hove** [comment]
Ok - I'll go the manual route then.

**Comment by joakim-hove** [comment]
> Ok - I'll go the manual route then.

Ehhh - is it possible to apply for a opm-data PR with updates to *all* the reference data[1]? As someone not doing this on a regular basis (and I guess I am actually number two on the list - I must admit I find this quite heavy going), 


[1]: The summary file `CASE.UNSMRY` should be updated - might be unmodified in some of the cases.

**Comment by akva2** [comment]
which test doesn't update the unsmr file ?

ref https://github.com/OPM/opm-simulators/blob/master/tests/update_reference_data.sh#L23
only the norne init test skips it afaict.

**Comment by joakim-hove** [comment]
> which test doesn't update the unsmr file ?

All tests update it - but for this particular PR it might be unchanged for a couple of the tests.

**Comment by akva2** [comment]
then i simply do not understand what you are asking for.

**Comment by joakim-hove** [comment]
> then i simply do not understand what you are asking for.

Just assistance with the manual grunt work / book-keeping required to run all the integration tests and update the reference data, without f...ing up somewhere.

**Comment by akva2** [comment]
status for the integration tests:
- polymer compares to eclipse data.
- spe compare to eclipse data, as well as opm data which is updated through the regression tests.
- norne plots a reference solution for opm along with eclipse and the executed runs. i have added the necessary fiddlery to support updating the reference file through the trigger in https://github.com/OPM/opm-simulators/pull/1044 but that will need @alfbr approval before i merge. an update should not be strictly required due to this PR as i guess it will plot the same data as before.

**Comment by joakim-hove** [comment]
> status for the integration tests:

OK - thank you for the update.

I'll merge - and take the flak if there is one.

**Comment by joakim-hove** [comment]
jenkins build this with downstreams update_data please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-data=179 please

**Pull request merged**
