### PR TITLE
Add ParseContext argument to SummaryConfig.

### PR DESCRIPTION
**Pull request by joakim-hove**
Followup to: https://github.com/OPM/opm-parser/pull/863

### CODE REVIEW

**Comment by jokva** [comment]
Fails now due to wrong constructor overload invocation.

**Comment by joakim-hove** [comment]
jenkins build this with opm-parser=863 please

**Comment by joakim-hove** [comment]
> Fails now due to wrong constructor overload invocation.

It fails on Travis - because of the interdependency between this PR and https://github.com/OPM/opm-parser/pull/863. I have not managed to trick jenkins into running this combination, but it _Works on my machine_&trade; - and should in my opinion be ready to merge.

**Comment by joakim-hove** [comment]
Thank you for merging.

**Pull request merged**
