### PR TITLE
Reapply keywords (WVPR + WVPT & WVPRT+FVPRT)""

### PR DESCRIPTION
**Pull request by joakim-hove**
Reverts OPM/opm-output#244

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-data=302 please

**Comment by atgeirr** [comment]
Looks ready to my eyes. Merge?

**Comment by joakim-hove** [comment]
> Looks ready to my eyes. Merge?

Yes - in she goes!

**Comment by andlaus** [comment]
I get some failures for the opm-simulators `compareECLFiles_flow+2D_H__` test on master:

```
49: Comparing 232 steps.
49: Keywords missing from one case: 
49: WVPR:INJE01 WVPR:PROD01 WVPT:INJE01 WVPT:PROD01 
49: Program threw an exception: [/home/and/src/opm-output/build-cmake/fake-src/opm/test_util/summaryRegressionTest.cpp:47] Different amount of keywords in the two summary files.
49: 1 summary keyword(s) exhibit failures
```

doesn't this PR need an updated reference solution`

**Comment by andlaus** [comment]
scratch that. I forgot to pull opm-data. (actually I pulled it but I was on a different branch.)

**Pull request merged**
