### PR TITLE
Added support for block variables in Summary.

### PR DESCRIPTION
**Pull request by joakim-hove**
Support for block variables BPR,BSWAT and BSGAS in summary output.

### CODE REVIEW

**Comment by jokva** [comment]
_Nice_. Looks good, looking forward to it.

**Comment by pgdr** [comment]
Apparently, these variables all have aliases.  Should we support them?

```
BSGAS = BGSAT
BSWAT = BWSAT
BPR   = BPRESSUR
```

**Comment by jokva** [comment]
I don't see the harm in that, considering it's just three extra lines in the dispatch table.

**Comment by joakim-hove** [comment]
> Apparently, these variables all have aliases. Should we support them?

I have silently amended and force pushed an update supporting the aliases.

**Comment by jokva** [comment]
Excellent. Merge now or whenever reference solutions are updated.

**Review by pgdr — APPROVED** [review]
merge at will

**Comment by akva2** [comment]
@joakim-hove data pr ready, do the appropriate build tests please (ie trigger jenkins)

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-data=141 please

**Comment by joakim-hove** [comment]
Hmmm - this fails with missing ewoms? http://80.240.129.131:8080/job/opm-output-PR-builder/18/

**Comment by akva2** [comment]
Yes. Somebody changed the order of things without updating all downstream lists. I have sent a pr against your branch to fix it here.

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-data=141 please

**Comment by akva2** [comment]
the upcoming error is caused by the shared libraries.. yet again. looking into it, i have no idea why it keeps changing

**Comment by akva2** [comment]
jenkins build this with downstreams opm-data=141 opm-common=212 please

**Pull request merged**
