### PR TITLE
fixed: sanity check size of data array

### PR DESCRIPTION
**Pull request by akva2**
This fixes the norne through flow/flow_mpi/flow_ebos after recent refactorings.

I am not sure if this is just a missing sanity check, a change in semantics or a broken deck. I have thus also opened https://github.com/OPM/opm-simulators/pull/1046 which makes sure the caller does not push the empty vectors in the first place.

### CODE REVIEW

**Comment by akva2** [comment]
@alfbr as requested.

**Comment by joakim-hove** [comment]
Can you explain the situation where this happens? My initial feeling is that this looks more like an internal error/bug which should lead to an exception.

**Comment by akva2** [comment]
at time step 1, after substep 0, the simulator pushes empty GIPG/OIP/et al fields into the output container. thus, the check for the field existence passes, but the data vector is empty.

**Comment by akva2** [comment]
typo. it's after the first substep which is labeled substep 0.

**Comment by joakim-hove** [comment]
> at time step 1, after substep 1, the simulator pushes empty GIPG/OIP/et al fields into the output container. thus, the check for the field existence passes, but the data vector is empty.

OK - but this is a simulator bug, we can merge the alternative code:

```C++
f (sim_value.size() < cells.size())
     throw std::runtime_error("Passing empty error to summary write");
```
but I see no reason to paper over simulator bugs in this way.

**Comment by akva2** [comment]
sure, you do as you see fit, i have offered solutions in both repos as well as played with open cards. a throw certainly does not solve the regression however.

**Comment by joakim-hove** [comment]
I'll call.

**Comment by akva2** [comment]
hold for a better error message please

**Comment by akva2** [comment]
there we go, sorry for delay, skype intervened
'Error: Program threw an exception: Wrongly sized data array passed to output for keyword GIPG, size=0, expected=3504.'

**Comment by joakim-hove** [comment]
Thank you; absolutely last nit-pick: `if (sim_value.size() != cells.size()) { ... `.

**Comment by akva2** [comment]
i was faster with my rewrite ;) (already there)

**Comment by akva2** [comment]
not sure how to address the test failure, to my uneducated eye it seems the input data is to blame ?

**Comment by akva2** [comment]
right. after closer inspection it seems that the throw is wrong. we are passed the global data, but cells only holds a subset (the region). i guess we can eat the slight overhead of a max_element here?

**Comment by joakim-hove** [comment]
> not sure how to address the test failure, to my uneducated eye it seems the input data is to blame ?

Ehhh - no; took me some to disentangle this too. The `cells` property is a a set of indices which should be summed over; the test should be: `if (sim_value.size() != args.grid.getNumActive()) { ... `

**Comment by akva2** [comment]
numActive is 999 in the test, not 1000.

**Comment by joakim-hove** [comment]
> numActive is 999 in the test, not 1000.

OK - *that* is input-data failure; I will make a PR for that.

**Comment by akva2** [comment]
surpassed by #163

**Pull request closed without merging**
