### PR TITLE
add multiconfiguration support to jenkins build script

### PR DESCRIPTION
**Pull request by akva2**
also unifies build.sh and build-pr.sh and gets rid of
build-opm-output.sh

Depends on https://github.com/OPM/opm-common/pull/169 and changes to the jenkins configuration at http://ci.opm-project.org

### CODE REVIEW

**Comment by akva2** [comment]
@joakim-hove due to this being sensitive to the order of changes and needing syncronized external changes to the jenkins server, i request authority to merge myself when deemed ready.

**Comment by akva2** [comment]
jenkins build this opm-common=169 please

**Comment by akva2** [comment]
this is ready for merge. i have made an attempt at jenkins to keep the builder working in the mean time, but no guarantees how well those attempts work.

**Comment by joakim-hove** [comment]
> due to this being sensitive to the order of changes and needing syncronized external changes to the jenkins server, i request authority to merge myself when deemed ready.

Yes - please merge!

**Pull request merged**
