### PR TITLE
Fix units for RS and RVwhen loading from restart.

### PR DESCRIPTION
**Pull request by joakim-hove**
Downstream fix: https://github.com/OPM/opm-simulators/pull/1008

Will probably also require updates to the reference data.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-simulators=1008 please

**Comment by atgeirr** [comment]
Jenkins did not seem to run this, but the result in the downstream run seem to confirm that the restart reference data must be updated. I do not quite understand all of it though: why did comparing RS output between Flow and ECL reference data succeed before? Or have we only been comparing against Flow references? @akva2?

**Comment by joakim-hove** [comment]
> Or have we only been comparing against Flow references? @akva2?

We are only comparing `flow` &lrarr; `flow`

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-simulators=1008 please

**Pull request merged**
