### PR TITLE
Fixes for warnings from static code analysis

### PR DESCRIPTION
**Pull request by akva2**
Question: Is suppression using inline comments acceptable? (last commit).

### CODE REVIEW

**Comment by joakim-hove** [comment]
So to answer question: I would prefer if it were fixed without comment based suppression, and I guess at least in this case that can be easily achieved?

**Comment by joakim-hove** [comment]
Not clear to me why it is failing - has a real problem been unearthed?

**Comment by joakim-hove** [comment]
Address the comments you agree with and merge when the test failure has been resolved.

**Comment by akva2** [comment]
failure needs investigation, i did not encounter it locally.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
i cannot reproduce the problem on either of my 2 machines, or 3 vms, or jenkins :/. valgrind is silent, so is gdb, with or without symbols.

are you sure travis is working? i see you are pulling packages from lots of different places. in particular pulling boost backports built with standard toolchain, and then pulling in a toolchain backport is rather live fast, die young kind of behavior.

**Comment by joakim-hove** [comment]
> i cannot reproduce the problem on either of my 2 machines, or 3 vms, or jenkins :/. valgrind is silent, so is gdb, with or without symbols.

OK - thank you for thorough investigations.

> are you sure travis is working?

I guess this question is not on the ultimate list of questions we are really certain about - I thought so.

> and then pulling in a toolchain backport is rather live fast, die young kind of behavior.

Good point.

**Pull request merged**
