### PR TITLE
Model2 missing out kws

### PR DESCRIPTION
**Pull request by jokva**
Support for GGORH, GWCTH, RGIP, FOIP and FGIP.

### CODE REVIEW

**Comment by joakim-hove** [comment]
A small leap for mankind - a significant step for summary support in opm!

**Comment by atgeirr** [comment]
I am pretty sure this PR is the reason Norne fails currently. I get an exception from Wells.hpp line 113, due to missing well name. I believe the cause of this is that the code iterates over completions from the region cache, which in turn was created from deck data (EclipseState). This, for some reason (bug or not) contains the "B-4H" well. The simulator passes no data for the well "B-4H" for the first timesteps, since it does not come into existence before day 143. This is enough to make it go boom, since it cannot find the well there.

I hesitate to propose reverting this PR, but unless a solution cannot be found rather quickly I fear we might have to. (Also: I cannot understand what the name of this PR has to do with its contents, so I had to search a bit before I found out this was the one...)

Suggestions welcome!

**Comment by atgeirr** [comment]
Another small note: this is not in the release branch, so it does not impact the release schedule.

**Comment by joakim-hove** [comment]
Can you post a backtrace? This is not release material anyway, so reverting is in my opinion not really an option?!

**Comment by atgeirr** [comment]
```
* thread #1: tid = 0xdb66c, 0x00007fff8ccdba01 libc++abi.dylib`__cxa_throw, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00007fff8ccdba01 libc++abi.dylib`__cxa_throw
    frame #1: 0x000000010012ebc8 flow`std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Opm::data::Well, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, Opm::data::Well> > >::at(this=0x00007fff5fbfb908 size=3, __k="B-4H") const + 168 at map:1591
  * frame #2: 0x0000000100799a7c flow`Opm::data::WellRates::get(this=0x00007fff5fbfb908, well_name="B-4H", completion_grid_index=508, m=gas) const + 60 at Wells.hpp:113
    frame #3: 0x000000010079a05e flow`Opm::(anonymous namespace)::quantity Opm::(args=0x00007fff5fbfaca8)::region_rate<(Opm::data::Rates::opt)4, false>(Opm::(anonymous namespace)::fn_args const&) + 462 at Summary.cpp:313
    frame #4: 0x00000001007921a1 flow`Opm::(anonymous namespace)::quantity Opm::(args=0x00007fff5fbfaca8)::region_production<(Opm::data::Rates::opt)4>(Opm::(anonymous namespace)::fn_args const&) + 17 at Summary.cpp:331
    frame #5: 0x000000010079b5cd flow`Opm::(anonymous namespace)::quantity std::__1::__invoke_void_return_wrapper<Opm::(anonymous namespace)::quantity>::__call<Opm::(anonymous namespace)::quantity (*&)(Opm::(anonymous namespace)::fn_args const&), Opm::(anonymous namespace)::fn_args const&>(Opm::(anonymous namespace)::quantity (*&&&)(Opm::(anonymous namespace)::fn_args const&), Opm::(anonymous namespace)::fn_args const&&&) [inlined] decltype(__f=0x0000000105fe5e98, __args=0x00007fff5fbfaca8)::quantity (*&)(Opm::(anonymous namespace)::fn_args const&)>(fp)(std::__1::forward<Opm::(anonymous namespace)::fn_args const&>(fp0))) std::__1::__invoke<Opm::(anonymous namespace)::quantity (*&)(Opm::(anonymous namespace)::fn_args const&), Opm::(anonymous namespace)::fn_args const&>(Opm::(anonymous namespace)::quantity (*&&&)(Opm::(anonymous namespace)::fn_args const&), Opm::(anonymous namespace)::fn_args const&&&) + 21 at __functional_base:416
    frame #6: 0x000000010079b5b8 flow`Opm::(anonymous namespace)::quantity std::__1::__invoke_void_return_wrapper<Opm::(__args=0x0000000105fe5e98, __args=0x00007fff5fbfaca8)::quantity>::__call<Opm::(anonymous namespace)::quantity (*&)(Opm::(anonymous namespace)::fn_args const&), Opm::(anonymous namespace)::fn_args const&>(Opm::(anonymous namespace)::quantity (*&&&)(Opm::(anonymous namespace)::fn_args const&), Opm::(anonymous namespace)::fn_args const&&&) + 40 at __functional_base:437
    frame #7: 0x000000010079b478 flow`std::__1::__function::__func<Opm::(anonymous namespace)::quantity (*)(Opm::(anonymous namespace)::fn_args const&), std::__1::allocator<Opm::(anonymous namespace)::quantity (*)(Opm::(anonymous namespace)::fn_args const&)>, Opm::(anonymous namespace)::quantity (Opm::(anonymous namespace)::fn_args const&)>::operator(this=0x0000000105fe5e90, __arg=0x00007fff5fbfaca8)(Opm::(anonymous namespace)::fn_args const&) + 56 at functional:1437
    frame #8: 0x0000000100793afd flow`std::__1::function<Opm::(anonymous namespace)::quantity (Opm::(anonymous namespace)::fn_args const&)>::operator(this=0x0000000105fe5e90, __arg=0x00007fff5fbfaca8)(Opm::(anonymous namespace)::fn_args const&) const + 141 at functional:1817
    frame #9: 0x0000000100793e7b flow`Opm::out::Summary::add_timestep(this=0x00000001148342f8, report_step=0, secs_elapsed=0, grid=0x00000001148341d8, es=0x0000000102039800, regionCache=0x0000000114834268, wells=0x00007fff5fbfb908, state=0x00007fff5fbfb920) + 843 at Summary.cpp:736
    frame #10: 0x00000001007880ec flow`Opm::EclipseWriter::writeTimeStep(this=0x0000000109e7eb80, report_step=0, isSubstep=false, secs_elapsed=0, cells=Solution @ 0x00007fff5fbfb920, wells=Opm::data::Wells @ 0x00007fff5fbfb908, write_float=true) + 6188 at EclipseWriter.cpp:805
    frame #11: 0x00000001004bd054 flow`Opm::BlackoilOutputWriter::writeTimeStepSerial(this=0x0000000114833a60, timer=0x00007fff5fbfed68, state=0x00000001085af9d0, wellState=0x00007fff5fbfce08, simProps=0x00007fff5fbfc0d0, substep=false) + 2212 at SimulatorFullyImplicitBlackoilOutput.cpp:379
    frame #12: 0x00000001004bc3e5 flow`Opm::BlackoilOutputWriter::writeTimeStepWithCellProperties(this=0x0000000114833a60, timer=0x00007fff5fbfed68, localState=0x00000001085af9d0, localWellState=0x00007fff5fbfce08, cellData=0x00007fff5fbfc0d0, substep=false) + 1365 at SimulatorFullyImplicitBlackoilOutput.cpp:350
    frame #13: 0x00000001004bbe4f flow`Opm::BlackoilOutputWriter::writeTimeStepWithoutCellProperties(this=0x0000000114833a60, timer=0x00007fff5fbfed68, localState=0x00000001085af9d0, localWellState=0x00007fff5fbfce08, substep=false) + 159 at SimulatorFullyImplicitBlackoilOutput.cpp:303
    frame #14: 0x0000000100112efd flow`Opm::SimulatorBase<Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >::run(this=0x000000010f2e3cc0, timer=0x00007fff5fbfed68, state=0x00000001085af9d0) + 8909 at SimulatorBase_impl.hpp:190
    frame #15: 0x000000010004c9b5 flow`Opm::FlowMainBase<Opm::FlowMain<UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >, UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >::runSimulator(this=0x00007fff5fbff760) + 917 at FlowMain.hpp:829
    frame #16: 0x000000010000ee8b flow`Opm::FlowMainBase<Opm::FlowMain<UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >, UnstructuredGrid, Opm::SimulatorFullyImplicitBlackoil<UnstructuredGrid> >::execute(this=0x00007fff5fbff760, argc=3, argv=0x00007fff5fbff918) + 2059 at FlowMain.hpp:157
    frame #17: 0x000000010000e602 flow`main(argc=3, argv=0x00007fff5fbff918) + 66 at flow.cpp:41
    frame #18: 0x00007fff8e98f5ad libdyld.dylib`start + 1
    frame #19: 0x00007fff8e98f5ad libdyld.dylib`start + 1
```

**Comment by atgeirr** [comment]
> reverting is in my opinion not really an option

I think that if a solution is not found in a day or so, we should, since everything that is (or should be...) tested on the real cases will grind to a halt.

**Comment by pgdr** [comment]
> > reverting is in my opinion not really an option
> 
> I think that if a solution is not found in a day or so, we should, since everything that is (or should be...) tested on the real cases will grind to a halt.

Which raises the question why these "real cases" are not part of the automated regression tests in the first place.

**Comment by atgeirr** [comment]
> Which raises the question why these "real cases" are not part of the automated regression tests in the first place.

They are: https://ci.opm-project.org/job/Norne-full-run/

With this PR it seems it was not checked before merging though. I think perhaps it is a little unclear what tests gets run by Travis under various circumstances? In any case, "jenkins run norne please" (and not "jenkins build this run norne please" as I recently learned) would catch this sort of thing so we should always use it for PRs changing the results or the output in any way.

**Comment by joakim-hove** [comment]
Let there be no doubt; this is a bug we have introduced, and a simple fix is forthcoming.

> They are: https://ci.opm-project.org/job/Norne-full-run/

I agree that there is a Jenkins test for running Norne, but when it is not part of the 100% normal `ctest` dance it gets considerably less exposure. That is an unavoidable fact - and personally I think the correct approach to this is to extract the failing behavior from the large case and integrate it into a normal test -  rather than trying to push for more active use of the Norne test on Jenkins. Creating a normal test reproducing this problem is currently underway for this bug.

> I think perhaps it is a little unclear what tests gets run by Travis under various circumstances?

Travis will run all the tests - including those which require opm-data, which are part of the opm-xxxx repositories; all the way down to opm-upscaling.

**Comment by atgeirr** [comment]
> Let there be no doubt; this is a bug we have introduced, and a simple fix is forthcoming

Great!

> I agree that there is a Jenkins test for running Norne, but when it is not part of the 100% normal ctest dance it gets considerably less exposure. That is an unavoidable fact

True, and that is why I suggested we should try to use the Jenkins Norne test a little more.

> and personally I think the correct approach to this is to extract the failing behavior from the large case and integrate it into a normal test - rather than trying to push for more active use of the Norne test on Jenkins. Creating a normal test reproducing this problem is currently underway for this bug.

I do not see a conflict between the two:
- running Norne a little more often than we have done previously as well as
- adding a normal (smaller) test for the particular bug (which is great).

They way I see it they are independent, and both are good!

**Comment by akva2** [comment]
my .02c; 

there are two kinds of tests (in the context);
1) those run by ctest - regression and unit tests
2) those not run by ctest - integration tests

currently there are 3 tests in the last category, spe, norne and polymer. these are too costly to run on a regular basis. still, due to the lmited coverage in regression tests i have opted to run them as part of the post-merge builder in opm-simulators, which maybe adds to the confusion.

as joakim says, it's bad to rely on an integration test to catch regressions, so a regression test should instead be added that covers the behavior that broke in the integration test. the integration test should be considered a guide for good regression tests, not an alternative to them. i'm sure a test which expose the problem can be deviced, a test that that runs in a couple of seconds.

**Comment by jokva** [comment]
> i'm sure a test which expose the problem can be deviced, a test that that runs in a couple of seconds.

This is true, and this test has been written (rather, it was already there but not triggered by the input).

**Pull request merged**
