### PR TITLE
Added INIT file output of PVTW.

### PR DESCRIPTION
**Pull request by joakim-hove**
WIP: Will add the saturation tables as well before it is complete.

### CODE REVIEW

**Comment by jokva** [comment]
Nice, merge when green. Will the reference sets have to be updated for this? The tests are failing all the way down there.

**Comment by joakim-hove** [comment]
@akva2: This PR is ready for merge, and requires testdata updates. You could use it for further testing of the system for auto-creating updated testdata.

**Comment by akva2** [comment]
jenkins build this with downstreams opm-common=225 opm-simulators=1038 update_data please

**Comment by akva2** [comment]
jenkins build this with downstreams opm-common=225 opm-simulators=1038 update_data please

**Comment by akva2** [comment]
jenkins build this with downstreams opm-common=225 opm-simulators=1038 update_data please

**Comment by akva2** [comment]
jenkins build this with downstreams opm-common=225 opm-simulators=1038 update_data please

**Comment by akva2** [comment]
jenkins build this with downstreams opm-common=225 opm-simulators=1038 update_data please

**Comment by akva2** [comment]
jenkins build this with downstreams opm-common=225 opm-simulators=1038 update_data please

**Comment by akva2** [comment]
there we go. sorry for all the noise, took me a while to realize the problem was a regression in https://github.com/OPM/opm-simulators/pull/1036

**Comment by akva2** [comment]
jenkins build this with downstreams opm-data=175 please

**Comment by joakim-hove** [comment]
Is someone waiting for me here?

**Comment by akva2** [comment]
it's certainly not waiting on me at least. @atgeirr no reason to hold this one is there?

**Comment by atgeirr** [comment]
> no reason to hold this one is there?

I have not looked at this at all. Should I?

**Comment by akva2** [comment]
probably not. nothing seems to stand in your way @joakim-hove :)

**Comment by joakim-hove** [comment]
> nothing seems to stand in your way @joakim-hove :)

OK - the reason I asked was that the commit message here: https://github.com/OPM/opm-data/pull/175 was in my opinion wrong; the reason should only be OPM/opm-output#150. But as long as that is not an indication of something wrong I will not let a commit message stop me?!

**Comment by akva2** [comment]
ah yes. you can consider redoing the data update. i had to include those other prs while testing.

**Comment by akva2** [comment]
wiki holds info on the how (or just monkey what i did above - it's simply including update_data in the trigger phrase)

**Comment by joakim-hove** [comment]
jenkins build this with downstreams update_data please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-data=175 please

**Comment by akva2** [comment]
jenkins build this with downstreams opm-data=176 please

**Comment by akva2** [comment]
sorry for jumping ni but there was a possibility for an unobvious error..

**Comment by akva2** [comment]
jenkins build this with downstreams opm-data=176 please

**Comment by akva2** [comment]
all happy - you should merge before it changes! ;)

**Comment by joakim-hove** [comment]
> all happy - you should merge before it changes! ;)

Thank you for the assistance - the `update_data` option is a tremendous improvement!

**Pull request merged**
