### PR TITLE
Silence warnings

### PR DESCRIPTION
**Pull request by atgeirr**
Minor fixes that should have absolutely no effect other than removing compile-time warnings. I hope this can get in when green, @andlaus, @joakim-hove?

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
Ping?

**Comment by andlaus** [comment]
from my POV, this can be also pushed into the release branch once it is in master.

**Comment by akva2** [comment]
just in case: nobody touches the branches before i say they are unfrozen please.

**Comment by andlaus** [comment]
> just in case: nobody touches the branches before i say they are unfrozen please.

ok, fine. will you do the cherry picking then? how do you want to be notified? Anyway, I'd also like to get OPM/opm-simulators#1146 into the release if it gets merged into master in time.

**Comment by akva2** [comment]
i will release the branches after i have built the rc1 packages, then maintainers (or more perhaps release manager) own the branches again. point is i cannot package a moving target. i'm ~ halfway there.

**Pull request merged**
