### PR TITLE
Res vol rate

### PR DESCRIPTION
**Pull request by lars-petter-hauge**
Sveinung did the major changes for reservoir volume so this pr requires PR: https://github.com/OPM/opm-output/pull/224
I'll rebase afterwards

### CODE REVIEW

**Comment by lars-petter-hauge** [comment]
Added field variables free and dissolved gas

**Comment by lars-petter-hauge** [comment]
Rebased on master.

**Comment by joakim-hove** [comment]
jenkins build this with downstreams update_data please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-data=296 please

**Pull request merged**
