### PR TITLE
Added well load test to restart testing.

### PR DESCRIPTION
**Pull request by joakim-hove**
Added call to load wells as test.

### CODE REVIEW

**Comment by joakim-hove** [comment]
@akva2: The second commit here is in your part of the woods.

**Comment by akva2** [comment]
Just suffered a horrible os crash so right now i am working on restoring from backup.. will look into it asap but probably monday..

**Comment by akva2** [comment]
looks fine.

**Comment by joakim-hove** [comment]
> looks fine.

I'll take that as a review :smile:

**Pull request merged**
