### PR TITLE
Extract Schedule and SummaryConfig.

### PR DESCRIPTION
**Pull request by joakim-hove**
Downstream of: https://github.com/OPM/opm-parser/pull/1138

Depends on:  https://github.com/OPM/opm-grid/pull/285

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-parser=1138 with downstreams pleas

**Comment by joakim-hove** [comment]
jenkins build this opm-parser=1138 with downstreams please

**Comment by joakim-hove** [comment]
@akva2: There is quite some boilerplate in this build request:
```txt
jenkins build this opm-parser=1138 with downstreams please
```
would it be possible simplify the grammar?

**Comment by akva2** [comment]
possible yes, more error prone, yes. you can send a pr to suggest your regular expression, it all sits in git (for the most part, the anchors are jenkins and please are used in some other places).

**Pull request merged**
