### PR TITLE
WIP Output solvent summary

### PR DESCRIPTION
**Pull request by totto82**
The following keywords are implemented
[F,G,W]N[P,I][R,T]
FNPR, WNIR etc.

NOTE 1: 
The total T keywords does not yet work as a fix in ert is needed. 
@joakim-hove Could you add NPT and NIT to the total_vars list in smspec_node.c 

NOTE 2:
The connection keywords are only partly implemented 
(CNFR, CNPT and CNIT) as they are not yet supported from the simulator
side.

### CODE REVIEW

**Comment by joakim-hove** [comment]
> The total T keywords does not yet work as a fix in ert is needed. 
> @joakim-hove Could you add NPT and NIT to the total_vars list in smspec_node.c

Yes - will do. Just to be absolutely certain, the keywords you are requesting are: `{FNPT,FNIT,WNPT,WNIT,GNPT,GNIT,CNPT,CNIT}`?

**Comment by totto82** [comment]
Yes.

**Comment by joakim-hove** [comment]
> @joakim-hove Could you add NPT and NIT to the total_vars list in smspec_node.c

Done: https://github.com/Ensembles/ert/pull/1241

**Comment by joakim-hove** [comment]
OK - this looks  perfectly fine; but please add a test - just extend the [test deck](https://github.com/OPM/opm-output/blob/master/tests/summary_deck.DATA) with some solvent related properties - and then actually [check them](https://github.com/OPM/opm-output/blob/master/tests/test_Summary.cpp). 

Since solvent properties is a bit off-the-beaten track I actually consider adding tests specially important.

**Comment by totto82** [comment]
Test is added. 

Note 1: Now output values are not necessarily positive (The CNFR keyword) Please double-check whether my logic here is correct. 
Note 2: I needed to add rates2.set( rt::gas, -20.2 /day) to make the tests pass before I started adding the solvent stuff.

**Comment by totto82** [comment]
@joakim-hove  Thanks for the fix in Ert. It works as expected.

**Comment by jokva** [comment]
Nice work. I do have a suggestion though: we can remove `crate_all` and rather introduce the unary operation `neg` (it used to be there, but it was removed as there used to be no need for it). That way the solvent completion rate function becomes `{ "CNFR", neg( crate< rt::solvent > ) }`

**Comment by totto82** [comment]
Do you mean

``` C++
{ "CNFR", sum ( neg ( injecrate <rt::solvent>), prodcrate <rt::solvent>) }
```

**Comment by jokva** [comment]
I suppose. Isn't the only difference between `crate_all` and `crate` that crate interprets negative input as production, and `crate_all` just returns as-is?

**Comment by totto82** [comment]
Here is a solution without `crate_all`

**Comment by jokva** [comment]
Still seems iffy - what's the flow rate meant to be anyway? The sum of production (negative) and injection (positive  completion rates? What does eclipse output when completions produce more than whatever's injected? Is that positive or negative?

**Comment by totto82** [comment]
The way I understand the CNFR keyword is that it return positive values for producing perforations and negative values for injecting perforations. (i.e the opposite of OPM) 
Since prodcrate and injecrate returns postive values or zero, the minus operator will make sure that 
a non-zero value with the correct sign is returned for both producing and injecting perforations.

**Comment by jokva** [comment]
Right, at the (fairly low cost) of doubling the work. Pretty elegant actually. Mind naming it `sub` instead of `minus`?

**Comment by totto82** [comment]
No problem.

**Comment by jokva** [comment]
Splendid!

**Comment by jokva** [comment]
I'll merge once the tests are green.

**Pull request merged**
