### PR TITLE
Add phases to summary_deck.DATA

### PR DESCRIPTION
**Pull request by anrdnet**
summary_deck.DATA used for tests doesn't contain any phases.

WCONHIST then sets control mode to ORAT, which doesn't make sense if we have no phases.

This is a problem for OPM/opm-parser#953.

### CODE REVIEW

**Comment by joakim-hove** [comment]
Thank you - this is obviously right?

**Comment by joakim-hove** [comment]
Thank you - this is obviously right?

**Comment by joakim-hove** [comment]
Will merge when I have access to a proper workstation.

**Comment by pgdr** [comment]
> Will merge when I have access to a proper workstation.

Not if I do it first.

**Pull request merged**
