### PR TITLE
Using constructor in default argument creation.

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by jokva** [comment]
Why? Genuinely curious if it makes a difference.

**Comment by joakim-hove** [comment]
> Why? Genuinely curious if it makes a difference.

Well - on Travis it actually does; don't ask me why.

**Comment by joakim-hove** [comment]
I'll self merge this now - as it resurrects the travis build chain.

**Comment by jokva** [comment]
I think it might be the defaulted Solution constructor in conjuction with using map. The default one should go, I'll submit a patch.

**Comment by atgeirr** [comment]
In general, inheriting from classes not designed to be base classes (such as map) carries a significant risk of surprises, although I am not sure that is what bit you this time.

**Pull request merged**
