### PR TITLE
Make sure RFT file is opened in correct mode.

### PR DESCRIPTION
**Pull request by joakim-hove**
Downstream of: https://github.com/OPM/opm-parser/pull/1127

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-parser=1127 with downstreams please

**Comment by joakim-hove** [comment]
jenkins build this opm-parser=1127 with downstreams please

**Comment by joakim-hove** [comment]
jenkins build this opm-parser=1127 with downstreams please

**Comment by joakim-hove** [comment]
jenkins build this opm-parser=1127 with downstreams please

**Comment by alfbr** [comment]
Huge thanks for the rapid effort! Successfully tested, merging as suggested.

**Pull request merged**
